version: '3.9'
services:
  web:
    build:
      context: ./web
    image: vision
    container_name: 'vision'
    restart: on-failure
    ports:
      - 80:3000
    environment:
      SP_HOST: steampipe
      SP_PASSWORD: ${SP_PASSWORD}
      COOKIE_PASSWORD: ${COOKIE_PASSWORD}
      DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?connection_limit=100'
    depends_on:
      - mysql
      - steampipe
      - batch
  batch:
    build:
      context: ./batch
    image: batch
    container_name: 'batch'
    restart: on-failure
    environment:
      NODE_ENV: 'production'
      SP_HOST: steampipe
      SP_PASSWORD: ${SP_PASSWORD}
      DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?connection_limit=100'
      SP_TTL: ${SP_TTL}
    depends_on:
      - mysql
      - steampipe
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: 'mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
  steampipe:
    build:
      context: ./steampipe
    image: steampipe
    container_name: 'steampipe'
    ports:
      - 9193:9193
      - 9194:9194
    environment:
      STEAMPIPE_DATABASE_PASSWORD: ${SP_PASSWORD}
      AWS_DEFAULT_REGION: 'ap-northeast-2'
    restart: on-failure
